name: artifact

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - 'x86_64-linux'
          - 'aarch64-linux'
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install -y qemu-user-static

      - uses: cachix/install-nix-action@v21
        with:
          extra_nix_config: |
            system = ${{ matrix.arch }}
      
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Building tarball for ${{ matrix.arch }}
        run: nix build

      - name: Uploading artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nixos-system-${{ matrix.arch }}.tar.xz
          path: result/tarball/nixos-system-${{ matrix.arch }}.tar.xz